
//  A color picker with a color generated by random alpha-numeric from the color palatte (array).

const hex = [0,1,2,3,4,5,6,7,8,9,'A', 'B', 'C', 'D', 'E', 'F'];

const btn = document.getElementById('btn');
const color = document.querySelector('.color');

btn.addEventListener('click', getRandomHex);

function getRandomHex() {
    let hexColor = '#';
    for(let i=0;i<6;i++) {
        const randomNum = Math.floor(Math.random() * hex.length);
        hexColor += hex[randomNum];
    }
    document.body.style.backgroundColor = hexColor;
    color.textContent = hexColor;
}
